### ISSUE TITLE
Not working in GNOME 3.34.2 on Pop!_OS 19.10

### ISSUE THREAD

**Issue by jamesganderton** [linniksa/nm-hide-unmanaged-gnome-shell-extension#4]
I've tried both branches (master and change-network-manager-import), and both just don't load.

![image](https://user-images.githubusercontent.com/43238056/78472637-7dbf9880-7732-11ea-992f-4bae469a582f.png)

The warning triangle tooltip reads "Error loading extension". Hopefully there is a fix for this?

**Comment by linniksa** [comment]
Hello
can you check version from #3 pull request ?

**Comment by jamesganderton** [comment]
This worked for me. Thank you!
