### ISSUE TITLE
Broken in gnome 40

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [linniksa/nm-hide-unmanaged-gnome-shell-extension#5]
there is an official port guide for gnome extensions to gtk4

**Comment by martinm1000** [comment]
Just edit metadata.json and add "40" as a supported version and it will work, as this extension doesn't use GTK anyway.

**Comment by validatedev** [comment]
Fixed by https://github.com/linniksa/nm-hide-unmanaged-gnome-shell-extension/pull/6
